apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-simon
spec:
  selector:
	matchLabels:
	app: app-simon
  replicas: 2
  template:
	metadata:
  	labels:
	app: app-simon
	spec:
  	containers:
  	- name: app-simon
    	image: wiktorvip/app-simon:latest
    	imagePullPolicy: Never
    	ports:
    	- containerPort: 6000
