apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: app-simon
  name: app-simon
spec:
  replicas: 2
  selector:
    matchLabels:
      app: app-simon
  strategy: {}
  template:
    metadata:
      labels:
        app: app-simon
    spec:
      containers:
      - image: wiktorvip/app-simon:latest
        name: app-simon

