apiVersion: v1
kind: Service
metadata:
  labels:
    app: app-simon
  name: lb-app-simon
spec:
  ports:
  - port: 6000
    protocol: TCP
    targetPort: 6000
  selector:
    app: app-simon
  type: LoadBalancer
status:
  loadBalancer: {}
